version: 0.0
os: linux
files:
  - source: /
    destination: /var/aws-deploy
hooks:
  BeforeInstall:
    - location: deploy/install.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: deploy/run.sh
      timeout: 120
      runas: ec2-user
  ValidateService:
    - location: deploy/validate.sh
      timeout: 60
      runas: ec2-user