version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm i -g pnpm
      - pnpm install
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
  build:
    commands:
      - echo Build started on `date`
      - pnpm run build
    post_build:
      commands:
        - echo Build completed on `date`  