version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1"
    AWS_ACCOUNT_ID: "126510223803"
    IMAGE_REPO_NAME: "test"
    IMAGE_TAG: "latest"
    CLUSTER: "demo-cluster"
    SERVICE: "demo-service"

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - npm i -g pnpm
      - pnpm install

  pre_build:
    commands:
      - echo Build started on `date`
      - pnpm run build
      - echo Logging in to Amazon ECR...
      - usermod -aG docker $USER                 
      - newgrp docker
      - aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 126510223803.dkr.ecr.us-east-1.amazonaws.com

  build:
    commands:
      - echo Creating docker image
      - docker build -t 126510223803.dkr.ecr.us-east-1.amazonaws.com/test:latest .
      - echo Copying docker image to repository
      - docker push 126510223803.dkr.ecr.us-east-1.amazonaws.com/test:latest
    post_build:
      commands:
        - echo Update Fargate service
        - aws ecs update-service --cluster demo-cluster --service demo-service --force-new-deployment 