name: CI Pipeline

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1 # Reemplaza con tu región AWS
      
    - name: Login to Amazon ECR
      run: aws ecr get-login-password --region us-east-1 | docker login --username AWS --password-stdin 415658325849.dkr.ecr.us-east-1.amazonaws.com
      
    - name: Build the Docker image
      run: |
        docker build -t 415658325849.dkr.ecr.us-east-1.amazonaws.com/cicd-pipeline .
        docker push 415658325849.dkr.ecr.us-east-1.amazonaws.com/cicd-pipeline:latest
